---
title: "LongerIntervals"
author: "Halil Bilgin"
date: "9 Nisan 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(pander)

source('../autoload.R', chdir=T)
library(doMC)
registerDoMC(cores = 4)

repetitions <- 50

db36 <- manipulations$getProcessedData(dbRaw[dbRaw$diyaliz_sure >= 36,])
db48 <- manipulations$getProcessedData(dbRaw[dbRaw$diyaliz_sure >= 48,])


```



```{r cars}
algorithms <- loadClassifiers(c('lda'))
allFeatures <- featureSelection$fm(db,F)


fm <- featureSelection$aic(c(allFeatures), scaledDb)


result <- data.frame(
  method=character(),
  Accuracy=numeric(),
  AccuracyNull=numeric(),
  Sensitivity=numeric(),
  Specificity=numeric(),
  Kappa=numeric()
)

```

## Including Plots

You can also embed plots, for example:

```{r pressure, echo=FALSE}
sapply(c('db'), function(dbName) {
  
  sapply(names(algorithms), function(algorithm) {
    classifier <- get('algorithms')[[algorithm]]
    features <- get('fm')
    for(i in 1:repetitions) {
      set.seed(seed+i+1000)
      tt <- manipulations$trainTest(get(get('dbName')), p=0.75)
      scaledTt <- manipulations$scaledTrainTest(tt$train, tt$test)
      
      control <- trainControl(method="none", allowParallel = T)
      
      fit <- classifier(scaledTt$train, features[[1]], method=algorithm,
                        trControl=control)
      confMatrix <- confusionMatrix(predict(fit, newdata=scaledTt$test),
                                    scaledTt$test$gfrloss2)
      
      assign("result", rbind(get('result'), data.frame(
        method=paste(algorithm, get('dbName')),
        Accuracy=confMatrix$overall['Accuracy'],
        AccuracyNull=confMatrix$overall['AccuracyNull'],
        Sensitivity=confMatrix$byClass['Sensitivity'],
        Specificity=confMatrix$byClass['Specificity'],
        Kappa=confMatrix$overall['Kappa']
      )), envir = .GlobalEnv)
      
    }
  })
})


```

```{r results}

result2 <- result[0, ]

c<-sapply(levels(result$method), function(method) {
  result <- get('result')
  x<- lapply(result[result$method == method,], function(x){
    if(! is.numeric(x)) {
      return(x[[1]])
    }
    tTest <- t.test(x)
    sMean <- round(tTest$estimate[[1]],3)
    sError <- round(tTest$estimate[[1]] - tTest$conf.int[1], 3)
    
    c(as.character(paste(sMean, '\u00B1', sError)))
    
  })
  
  levels(x$method) <- levels(result$method)
  x <- data.frame(x, stringsAsFactors=FALSE)
  assign('result2', rbind(get('result2'), x), envir = .GlobalEnv)

})
cat(paste('## Running lda and glm ',repetitions,' times.'))
knitr::kable(result2, row.names = F)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
