---
title: "ModelComparison-ScaledData"
author: "Halil Bilgin"
date: "31 Mart 2017"
output:
  word_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(pander)
source('../autoload.R', chdir=T)
```

## Model comparison

This report compares different algorithms and feature sets forPolycystic kidney disease GFRLOSS classification problem.

# Models to be compared
```{r algorithms}
  algorithms <- c('svmRadial', 'lda', 'glm', 'nb', 'rf')
  
  algorithms <- loadClassifiers(algorithms)
```

## Set resamples
```{r trainControl}
  
  cat('Constant Seed:', seed, '\n')
  library(doMC)
  registerDoMC(cores = 2)
  set.seed(seed)
  
  control <- trainControl(method="LOOCV", 
                          allowParallel = T)
  
  cat('Method:', control$method, 'Number:', control$number, ' Repeats:',control$repeats, 'Training Percentage:', control$p)
  
```

## Formula with all features
``` {r allFeatures}
  print(featureSelection$fm(db), showEnv=F)
```

## Model comparisons with different sets of features

```{r featureSelection, echo=F, include=FALSE}
  scopes <- c(featureSelection$fm(db,F), featureSelection$fm(db,T))

  features <- featureSelection$lasso(scopes[0:1], scaledDb)
  features <- append(features, featureSelection$aic(scopes, scaledDb))
  
  ## Adding all features without selections.
  features <- append(features, list(as.factor(gfrloss2)~.))
  names(features) <- c('LASSO(ALL)', 'AIC(ALL)', 'AIC(ALL+ALL^2)', 'ALL')

```

#### Fitting models..
``` {r fitting models, include=FALSE}
  allFits <- list()
  
  ## creating a list that will contain fits
  for(feature in features) {
    fits <- list()
    # Run all algorithms for selected feature set
    
      for(i in 1:length(algorithms)) { 
      set.seed(seed)
      
      methodName <- names(algorithms)[i]
      classifier <- algorithms[[i]]
      fit <- classifier(trData=scaledDb, fm=feature,
                        method=methodName, metric='Accuracy',
                        trControl=control, tuneLength=20)
      
      fits <- append(fits, list(fit))
      }
    names(fits) <- names(algorithms)
    
    allFits <- append(allFits, list(fits))
  }
  
  names(allFits) <- names(features)
```

#### Model Comparison
```{r modelComparison}
  for(i in 1:length(allFits)) {
    
    fits <- allFits[[i]]
    featureName <- names(allFits)[i]
    
    pandoc.header(featureName, level=2)
    
    print(features[[i]], showEnv=F)
    
    ## Get results for each resample 
    resampleResults <- resamples(fits, decreasing=T, metric='Accuracy')
    
    # box and whisker plots to compare models
    scales <- list(x=list(relation="free"), y=list(relation="free"))
    
    print(bwplot(resampleResults, scales=scales, main=featureName))
    
  }
```


